# Generated by Django 5.0.2 on 2024-04-11 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaDesparacitacion',
            fields=[
                ('codigo_ficha_desparacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('via_administracion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('codigo_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('codigo_propietario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Propietarios',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('codigo_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHora', models.DateTimeField()),
                ('razon_cita', models.CharField(max_length=255)),
                ('codigo_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.mascota')),
                ('codigo_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionPropietarioMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.mascota')),
                ('codigo_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.propietario')),
            ],
        ),
    ]
