# Generated by Django 5.0.2 on 2024-04-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propietario',
            options={},
        ),
    ]
