# Generated by Django 5.0.2 on 2024-04-12 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0002_alter_propietario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionpropietariomascota',
            options={'verbose_name_plural': 'Asignacion de Propietario y Mascota'},
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='fichadesparacitacion',
            options={'verbose_name_plural': 'Fichas de Desparacitacion'},
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'verbose_name_plural': 'Mascotas'},
        ),
        migrations.AlterModelOptions(
            name='propietario',
            options={'verbose_name_plural': 'Propietarios'},
        ),
    ]
