# Generated by Django 5.0.2 on 2024-04-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0004_rename_cita_citas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='estado',
            field=models.CharField(choices=[('done', 'DONE'), ('canceled', 'CANCELED')], default='done', max_length=10),
        ),
        migrations.AddField(
            model_name='desparasitaciones',
            name='estado',
            field=models.CharField(choices=[('completed', 'completado'), ('incompleted', 'no completado')], default='completed', max_length=11),
        ),
        migrations.AddField(
            model_name='duenos',
            name='estado',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='estado',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=10),
        ),
    ]
